FROM golang:1.18-alpine AS build-env

WORKDIR /projects/starter
ENV GOOS=linux
ENV GOARCH=386
ENV CGO_ENABLED=0

RUN apk --update add git

COPY ./starter .

RUN go build -o helloapp ./cmd/helloapp/main.go

FROM scratch
COPY --from=build-env /projects/starter/helloapp .

ENTRYPOINT ["./helloapp"]
