FROM golang:1.10-alpine AS build-env

RUN apk --update add git
RUN go get -u github.com/golang/dep/cmd/dep

ENV GOOS=linux
ENV GOARCH=386

WORKDIR /go/src/go-rest-starter/go/src/starter
COPY ./go/src/starter .
RUN dep ensure
RUN go build -o goapp ./cmd/apiapp/main.go

FROM scratch
COPY --from=build-env /go/src/go-rest-starter/go/src/starter/goapp .

ENTRYPOINT ["./goapp"]