FROM golang:1.11-alpine AS build-env

RUN apk --update add git
# RUN go get -u github.com/golang/dep/cmd/dep

ENV GOOS=linux
ENV GOARCH=386
ENV CGO_ENABLED=0

WORKDIR /projects/starter
COPY ./starter .
# RUN dep ensure
RUN go build -o helloapp ./cmd/helloapp/main.go

FROM scratch
COPY --from=build-env /projects/starter/helloapp .

ENTRYPOINT ["./helloapp"]