version: '3'
services:
  api:
    build: .
    image: go-starter-api
    ports:
      - 8000:8000
      - 2345:2345
    depends_on:
      - db
    volumes:
      - ./starter:/projects/starter
      - "/go"
    # command: tail -f /dev/null
    command: sh -c './wait-for.sh db:3306 -- chmod +x ./start.sh && ./start.sh'
    env_file:
      - .env
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hello
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080