version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: go-starter-api
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hello
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080