settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: helloapp
  path: .
  commands:
    install:
      status: false
    run:
      status: true
      method: ./helloapp
    build:
      status: true
      method: go build -o helloapp cmd/helloapp/main.go
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
